version: '3.8'

services:
  postgres:
    image: postgres:17-alpine
    container_name: student-scoring-postgres
    environment:
      POSTGRES_DB: studentscoring
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # pgAdmin for database management
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: student-scoring-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@studentscoringapp.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  # Spring Boot Application
#  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: student-scoring-app
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/studentscoring
#      SPRING_DATASOURCE_USERNAME: postgres
#      SPRING_DATASOURCE_PASSWORD: password
#      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
#    ports:
#      - "8080:8080"
#    depends_on:
#      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  default:
    driver: bridge